### ISSUE TITLE
加入后遭遇白屏

### ISSUE THREAD

**Issue by Hippoom** [TheBund1st/pdd-help-desk#1]
How to reproduce:
一开始进入，然后不操作关闭了。再进入所有页面都是白屏

![image](https://user-images.githubusercontent.com/4027418/47700133-5a94dd80-dc50-11e8-88b1-8b4a9dddfa34.png)

**Comment by CanvasCao** [comment]
白屏的原因是因为打开小程序时处于弱网环境 请在网络环境良好的地方重新登录
如果依然可以重复浮现这个问题 请联系开发者本人 微信号：bb1174478646

**Comment by Hippoom** [comment]
Please reopen if more details can be provided
